# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 07:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_myuser_myuserchange_pw_myuseredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='Firstname',
            new_name='Username',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='Lastname',
        ),
    ]
